# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: pool
    type: object
    default:
      vmImage: ubuntu-20.04
  - name: arch
    type: string
    default: amd64

jobs:
- job:
  displayName: Build-${{ parameters.arch }}
  timeoutInMinutes: 600
  pool: ${{ parameters.pool }}
  container:
    image: debian:bullseye
    options:  "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: 'Install Sudo in container'
  - script: |
      sudo mkdir -p $HOME
      sudo chown $USER $HOME
      sudo apt-get update
      sudo apt-get install -y cmake git make build-essential quilt debhelper bc python3 python3-pip sudo libssl-dev libgcc-10-dev
      sudo apt-get install -y clang
      sudo apt-get install -y openssl libssl-dev libssl1.1
      sudo apt-get install -y dh-exec dh-runit libaudit-dev libedit-dev libfido2-dev libgtk-3-dev libkrb5-dev
      sudo apt-get install -y libwrap-dev pkg-config
      sudo apt-get install -y libpam-dev libselinux1-dev libsystemd-dev libwrap0-dev

      # Build Golang
      sudo apt-get install -y golang
 
      # Build Python
      sudo apt-get install -y lsb-release sharutils libreadline-dev libncursesw5-dev  libbz2-dev liblzma-dev libgdbm-dev libdb-dev tk-dev blt-dev  libexpat1-dev libmpdec-dev libbluetooth-dev locales-all libsqlite3-dev media-types
      sudo apt-get install -y time net-tools xvfb systemtap-sdt-dev python3-sphinx python3-docs-theme texinfo
      sudo pip3 install blurb
      mkdir -p $(Pipeline.Workspace)/target
    displayName: 'Install packages'
  - checkout: self
    submodules: true
  - script: |
      cd src/SymCrypt
      git submodule update --init -- jitterentropy-library
    displayName: 'Checkout Symcrypt submodules'
  - script: |
      set -ex
      sudo mkdir -p $HOME
      sudo pip3 install -r src/SymCrypt/scripts/requirements.txt
      ARCH=${{ parameters.arch }} make all
    displayName: 'Build'
  - publish: $(System.DefaultWorkingDirectory)/target
    artifact: fips-symcrypt-${{ parameters.arch }}
    displayName: "Archive packages"
