# krb5

KRB5_VERSION = 1.18.3-6+deb11u4
KRB5_VERSION_FIPS = $(KRB5_VERSION)+fips
KRB5 = libk5crypto3_$(KRB5_VERSION_FIPS)_$(ARCH).deb
$(KRB5)_SRC_PATH = $(SRC_PATH)/krb5

MAIN_TARGETS += $(KRB5)
$(KRB5)_DERIVED_DEBS =
