# SYMCRYPT_OPENSSL

SYMCRYPT_OPENSSL_VERSION = 0.1
SYMCRYPT_OPENSSL = symcrypt-openssl-$(SYMCRYPT_OPENSSL_VERSION)_$(ARCH).deb
$(SYMCRYPT_OPENSSL)_SRC_PATH = $(SRC_PATH)/SymCrypt-OpenSSL-Debian
$(SYMCRYPT_OPENSSL)_MAKEFILE = $(SYMCRYPT_OPENSSL)_SRC_PATH/Makefile

MAIN_TARGETS += $(SYMCRYPT_OPENSSL)
