# SYMCRYPT_OPENSSL

SYMCRYPT_OPENSSL_VERSION = 0.1
SYMCRYPT_OPENSSL = symcrypt-openssl_$(SYMCRYPT_OPENSSL_VERSION)_$(ARCH).deb
$(SYMCRYPT_OPENSSL)_SRC_PATH = $(SRC_PATH)/SymCrypt-OpenSSL-Debian

MAIN_TARGETS += $(SYMCRYPT_OPENSSL)
$(SYMCRYPT_OPENSSL)_DERIVED_DEBS += symcrypt-openssl-dbg_$(SYMCRYPT_OPENSSL_VERSION)_$(ARCH).deb
